# Generated by Django 6.0.6 on 2026-06-15 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Serial number or hardware UUID', max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('USB', 'USB / External Mass Storage'), ('ANDROID', 'Android Device')], max_length=15)),
                ('label', models.CharField(blank=True, help_text='e.g., Samsung S23, SanDisk 64GB', max_length=255, null=True)),
                ('mount_point', models.CharField(blank=True, help_text='e.g., E:\\ or ADB device ID', max_length=50, null=True)),
                ('status', models.CharField(choices=[('DETECTED', 'Detected / Idle'), ('SCANNING', 'Scan In Progress'), ('COMPLETED', 'Scan Completed'), ('FAILED', 'Scan Failed')], default='DETECTED', max_length=15)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForensicArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Summary of the finding (e.g., Cached Browser Password Found)', max_length=255)),
                ('category', models.CharField(help_text='e.g., Browser Cache, Application Log, System Settings', max_length=100)),
                ('severity', models.CharField(choices=[('INFO', 'Information / Log'), ('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk / Exposure')], default='INFO', max_length=10)),
                ('extracted_data', models.JSONField(help_text='Raw or parsed structure of the forensic artifact')),
                ('timestamp_observed', models.DateTimeField(blank=True, help_text='The historic log timestamp from the target device', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this tool parsed and saved the data')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='forensics.targetdevice')),
            ],
        ),
    ]
