# Generated by Django 6.0.6 on 2026-06-15 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forensicartifact',
            name='timestamp_observed',
        ),
        migrations.RemoveField(
            model_name='targetdevice',
            name='label',
        ),
        migrations.AddField(
            model_name='forensicartifact',
            name='is_spoofed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forensicartifact',
            name='sha256_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='forensicartifact',
            name='true_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='targetdevice',
            name='case_notes',
            field=models.TextField(blank=True, default='Standard automated digital forensic acquisition triage routine.'),
        ),
        migrations.AddField(
            model_name='targetdevice',
            name='case_number',
            field=models.CharField(default='CASE-2026-001', max_length=100),
        ),
        migrations.AddField(
            model_name='targetdevice',
            name='investigator_name',
            field=models.CharField(default='Lead Analyst', max_length=255),
        ),
        migrations.AlterField(
            model_name='forensicartifact',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='forensicartifact',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='forensicartifact',
            name='extracted_data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='forensicartifact',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low Operational Risk'), ('HIGH', 'High Security Flag'), ('CRITICAL', 'Critical Evasion Leak')], default='LOW', max_length=50),
        ),
        migrations.AlterField(
            model_name='forensicartifact',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='targetdevice',
            name='detected_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='targetdevice',
            name='device_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='targetdevice',
            name='device_type',
            field=models.CharField(choices=[('USB', 'USB Storage Media'), ('ANDROID', 'Android Mobile Device')], max_length=50),
        ),
        migrations.AlterField(
            model_name='targetdevice',
            name='mount_point',
            field=models.CharField(default='E:\\', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='targetdevice',
            name='status',
            field=models.CharField(choices=[('IDLE', 'Idle Registry'), ('SCANNING', 'Auditing Targets...'), ('COMPLETED', 'Analysis Complete'), ('FAILED', 'Execution Failure')], default='IDLE', max_length=50),
        ),
    ]
