# Generated by Django 6.0.6 on 2026-06-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0002_remove_forensicartifact_timestamp_observed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forensicartifact',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=50),
        ),
        migrations.AlterField(
            model_name='targetdevice',
            name='case_notes',
            field=models.TextField(blank=True, default='Standard forensic triage.'),
        ),
        migrations.AlterField(
            model_name='targetdevice',
            name='mount_point',
            field=models.CharField(default='E:\\', max_length=255),
        ),
        migrations.AlterField(
            model_name='targetdevice',
            name='status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('SCANNING', 'Scanning'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IDLE', max_length=50),
        ),
    ]
